### ISSUE TITLE
Interoperability issue with Arduino GSM 14400 MKr

### ISSUE THREAD

**Issue by DroneUniversity** [budryerson/TFMini-Plus#12]
HI,

I did perform the changes to the prinf library but the specic but cannot compile on the specific board.
Have anyone tried using this board?

Thanks
Spyros

**Comment by budryerson** [comment]
Hey Spyros,

I have not used the MKR GSM 1400 board.  I understand that additional installations for the Arduino IDE are required.  But I am not entirely clear as to the nature of the problem you're experiencing.

Is it problems with `printf.h` or the TFMini-Plus library or the IDE itself?  Please send me more information about your workflow, your results and especially the "changes" you say you made,

We'll fix this, I am sure.

Thanks,
Bud Ryerson
San Francisco
