### ISSUE TITLE
How do you count people in/out ?

### ISSUE THREAD

**Issue by JpEncausse** [budryerson/TFMini-Plus#17]
Hello,

How do you count people if they are In and Out with a single sensor ?
https://www.youtube.com/watch?v=xULR1e4NWso

How do you track multiple people at the same time ?

Thanks !

**Comment by budryerson** [comment]
You can tell whether a person is coming In or Out by measuring whether an object is moving away from the sensor or toward it.

I believe it's impossible to track multiple people with a single sensor.
