### ISSUE TITLE
Change mode from UART to I2C!

### ISSUE THREAD

**Issue by tusharvb19** [budryerson/TFMini-Plus#24]
Help needed!!!
Hi, I did try to change the mode form UART to I2C by following this guide:
https://discuss.ardupilot.org/t/benewake-tfmini-s-how-to-issue-commands-to-change-from-uart-to-i2c/57495/49
Here is the error screen snip:

![image](https://user-images.githubusercontent.com/20925909/106414738-5f6e1a80-6473-11eb-8ff7-bd4797911815.png)

**Comment by budryerson** [comment]
Hello,
I'm happy to see that you got help with your problem back in February on the ArduPilot website.
https://discuss.ardupilot.org/t/benewake-tfmini-s-how-to-issue-commands-to-change-from-uart-to-i2c/57495/114
I'm sorry that I wasn't able to help.  Good luck with your project.
Bud Ryerson
