### ISSUE TITLE
'fdevopen' was not declared in this scope

### ISSUE THREAD

**Issue by jimbobhunter** [budryerson/TFMini-Plus#26]
Hi. Looking forward to using the library but I get this error when trying to compile for M5Atom.

**Comment by budryerson** [comment]
Jim Bob,
I look forward to helping, but I'm going to need a little more information.
Please zip up the sketch that your using and a file with the output that your getting.
Email it to me:  bud-at-budryerson-dot-com.
We will fix this.
Thanks,
Bud Ryerson
San Francisco

**Comment by jimbobhunter** [comment]
> Jim Bob,
> I look forward to helping, but I'm going to need a little more information.
> Please zip up the sketch that your using and a file with the output that your getting.
> Email it to me: bud-at-budryerson-dot-com.
> We will fix this.
> Thanks,
> Bud Ryerson
> San Francisco

Sent, thanks Bud!

**Comment by default-student** [comment]
I dont know how this fixes the problem.
Im afraid i ran into it as well

**Comment by budryerson** [comment]
Back in February of 2021, Jim Bob Hunter sent me his error messages and his code as I requested.  I sent him the following suggestion.
```
James,

You are not using 'printf' but you left in all the odd formatting characters.
Such as in Line 74:
    Serial.print( "%1u.", tfmP.version[ 0]);
"%1u." is an instruction to print the data as a single character of an unsigned integer.
It doesn't make any sense to your compiler.

You should format the data into a string and then print the string.

Bud 
```
Maybe you have the same problem and maybe the same advice will help you as well.  Please  let me know.

Bud Ryerson
San Francisco

**Comment by default-student** [comment]
Replacing all the printf's with Serial.print fixed it!
This doesnt fix the underlying issue tho.


Thank you for your response.
