### ISSUE TITLE
TFmini plus timeout?

### ISSUE THREAD

**Issue by didi1150** [budryerson/TFMini-Plus#27]
I'm getting the messages: 

TFMPlus Library Example - 18JUN2020
System reset: Status: TIMEOUT
 00 00 00 00 00 00 00 00
Firmware version: Status: TIMEOUT
 00 00 00 00 00 00 00 00
Data-Frame rate: Status: TIMEOUT
 00 00 00 00 00 00 00 00
Status: HEADER
Data: 00 00 00 00 00 00 00 00 00

And then it continues printing the last two lines.

I'm using the example code.

**Comment by budryerson** [comment]
It appears that you are not communicating with the device.
Forgive me, but please answer a couple of necessary questions:
1) Is the TFMini-Plus turned on?  Can you see the red glow?
2) Did the device communicate correctly with the Benewake GUI?
3) Which Arduino are you using?
4) Are you using hardware or software serial?
5) Are the RX./TX lines are connected correctly?
6) Can you send me a picture of your setup?
I'm sure we'll fix this.
Bud Ryerson
San Francisco

**Comment by didi1150** [comment]
Im using the arduino mega. And is it possible to change the pins of the tfmini plus? Because you could set them in the ide when using the tfmini lib.

**Comment by didi1150** [comment]
Oh and the tfmini plus doesnt glow

**Comment by didi1150** [comment]
Oh and Im using software serial. As far as i know the rx tx lines are connected correctly.

**Comment by didi1150** [comment]
Oh and also I modified the Serial2 to mySerial, because it always says 'Serial2' was not declared in this scope when I use Serial2.

**Comment by didi1150** [comment]
Ok Ive done it, the sensor is onw working

**Comment by didi1150** [comment]
I just connected rx and tx wrongly.
