### ISSUE TITLE
What is this library called in the Arduino examples

### ISSUE THREAD

**Issue by mudmin** [budryerson/TFMini-Plus#39]
Sorry, this could be the dumbest thing I ever asked, but I see that you have an example sketch, yet it's not showing up under File->Examples in the IDE and I can't find your library after installing it.  What is it called?

**Comment by budryerson** [comment]
It's called `TFMP_example.ino`.  The `examples` folder also includes `printf.h`, a common print formatting header file that you should include in the same folder with the sketch.
I can't imagine why it didn't show up.  Did you try downloading the library as a zip file?
Please let me know.

Bud Ryerson
San Francisco

**Comment by mudmin** [comment]
I downloaded it through the library manager.  The example is there if I navigate to C:\Users\PcName\Documents\Arduino\libraries\TFMPlus\example but it isn't showing up under the "examples" in the IDE itself.  Thanks for the quick response!

**Comment by budryerson** [comment]
I deleted my TFMPlus library and installed it again using the Arduino IDE Library Manager.  The resulting `examplers` folder contained both the example sketch and the `printf.h` file.  I don't know what to tell you except to suggest that you delete the library and try re-installing it.  If you do, please let me know whether that works for you.
Thanks,
Bud

**Comment by mudmin** [comment]
Hi. I'm sorry. I probably wasn't clear. I see there is an example sketch included in the library, however when I go to File->Examples->{libraryname}  your library/example isn't there.  I just did a tutorial on youtube showcasing your library, but I had to tell people to hunt around in the library folder to grab it.  

I've only written one library for the IDE, but my example showed up automatically. Yours didn't for some reason.

**Comment by budryerson** [comment]
I was not aware of the 'Examples' selection under the 'File' drop-down menu in the Arduino IDE.  Sure enough, not one example from any of my libraries shows up there.  I must be doing something wrong.  I will fix that... somehow.

Thank you for your gentle (and repeated) guidance.  Obviously, I have much to learn.  Please provide a link to your YouTube tutorial.

Bud Ryerson
San Francisco

**Comment by mudmin** [comment]
I see you found my video :)  Yeah. I have no idea how the whole example script thing works, but I just wanted to let you know that I REALLY appreciate your libraries.  Those units are very cool, but there's not a lot of info out there on getting them working quickly.  Thanks for all you do.

**Comment by budryerson** [comment]
I have corrected the library.  Examples codes are now available in the Arduino IDE drop down menu as they should have been.
Lesson learned. Thank you for your help. <br />
Bud
