### ISSUE TITLE
2x (or more) devices on one board?

### ISSUE THREAD

**Issue by samuk** [budryerson/TFMini-Plus#40]
Is there any example code for connecting two TFMini+ devices to a single board using this library?

**Comment by budryerson** [comment]
This library is for the **Serial UART** mode of the device.  Most Arduino boards have only a single hardware serial port.  Using the Arduino **SoftwareSerial** library, multiple software serial ports can be implemented and a separate device can be connected to each one.  I strongly do not recommend doing that.  I do not know of any example code for that.

I recommend using the **TFMPI2C** library and the I2C communications mode of the **TFMini-Plus LiDAR** device.  I have personally attached up to three devices at a time on the I2C bus.  I would be happy to send you that code.

Best of luck,
Bud Ryerson
San Francisco

**Comment by samuk** [comment]
Ah makes sense. Thanks. Would love to see the other example code please.

**Comment by budryerson** [comment]
Try this out ... after you assign and test unique and proper slave addresses for each of your LiDARs, of course.
Also, be sure you've got the latest version (1.7.0) of the TFMPI2C library installed.

[TFMP_3unit.zip](https://github.com/budryerson/TFMini-Plus/files/7636030/TFMP_3unit.zip)

**Comment by samuk** [comment]
Nice one thanks. I don't have devices yet, but now I know it works I'll order some. 

Are both the lib https://github.com/samuk/TFMini-Plus-I2C and the example Zip above MIT/GPL licenced?

**Comment by budryerson** [comment]
I'm not sure.  Do I need a license?  Do they need to be licensed?  Please tell me more.

**Comment by samuk** [comment]
I'd prefer it if you had one. It would give confidence that you won't charge me some 'license fee' in the future.

I like https://mit-license.org/ personally.

**Comment by digamesystems** [comment]
I'm using an ESP32 module on a project. It has 2 UARTs in addition to the serial port used for loading code / debugging. I was able to take Bud's library and talk to both of them simultaneously by declaring two instances of the `TFMPlus` class.

You might be able to adapt this to something like an Arduino Mega, but I haven't tried that. 

https://github.com/digamesystems/esp32_dual_lidar_example

(MIT license)

:)

Regards,
John

**Comment by budryerson** [comment]
Thanks for the credit, John.  "My heart soars like a hawk." - Old Lodge Skins (Chief Dan George)

**Comment by digamesystems** [comment]
Credit where credit is due! It's nice work. I saw your exchange with @samuk and did the little writeup with code I had from the beginning of my project. 

I can get a picture or two of the setup if folks are interested.

**Comment by budryerson** [comment]
Here's a Due, driving a stepper motor with two TFMini-S mounted back-to-back.  The SDA & SCL lines separate into a heart shaped pattern (gotta keep 'em apart!) leading from a slip ring to a small bread board.  That board also connects an optical sensor on the side of the rig to provide a position sync mark.  Is this what you were asking for?  Let me know if I can bore you with some code. :smile:

![lastGasp_25](https://user-images.githubusercontent.com/7094018/165643909-a3632cac-f1c4-4959-8fc1-f0c90a64d5c6.png)

https://user-images.githubusercontent.com/7094018/165644631-be9fccc5-2fa9-43fb-8eb1-622ea5a05a8a.mp4

**Comment by digamesystems** [comment]
Hi, Bud.
I took a look at the code you sent Samuk. I see that you are using the three LIDARs in 'untriggered' ('self-triggered') mode. Have you tried running in externally triggered mode? I have my setup working in that mode to save power (my application is battery powered)  but occasionally the system gets into a state where one of the sensors is no longer responding. Oddly, the data and status codes I keep receiving from a call to the `getData(..., addr)` function are the same as the last valid reading I received from the sensor. This makes it tough to tell when it's hung up. Have you any tips for detecting / recovering from this? 
Thanks!

**Comment by Firestarter97** [comment]
@budryerson Do you by any chance have a schematic as to how you connected your 3 tfmini plus setup to a single arduino uno board? Thanks!

**Comment by budryerson** [comment]
Dear Firestarter (Firestarter?),
Enable the I2C interface on all three devices. Assign each one a unique address.  Connect the four wires (GND, VCC, SDA & SCL) from each device in parallel and attach them to the UNO.  Keep the I2C lines short and try to keep the SCL and SDA lines separate in order to minimize cross talk.  Do you really need a schematic for that?  Let me know.
Bud

**Comment by Firestarter97** [comment]
@budryerson Thanks for the explanation! I won't be needing the schematic. One more question, concerning keeping I2C lines short. Would it be fine to use 12 to 18 inches? Thanks again!

**Comment by digamesystems** [comment]
@Firestarter97 I was curious about this, too and ran across this reference from TI that goes into detail on some of the issues to watch out for. https://www.ti.com/lit/an/slyt770/slyt770.pdf?ts=1656812624198 

From their doc:

 _"The best approach to resolving crosstalk is to place small series resistors on the SDA/SCL lines and to minimize the parasitic bus capacitance between the SDA and SCL traces."_

Here, they are talking about PCB design. -- For leads out in space, I might try making the SDA/SCL lines twisted pairs, each with their own ground line.
 
@budryerson what are your thoughts, Bud?

**Comment by budryerson** [comment]
Firestarter & Digame - The shorter the better.  Remember, this bus was developed for communication between chips on a PCB.  Some people claim relatively long distances with shielded cabling technique.  For me, I think 18 inches is pushing it.  As shown in the TI article, a scope is very helpful in this situation.  Good luck, and please let me know how it turns out.  - Bud

**Comment by Firestarter97** [comment]
@budryerson Hello, I only recently was able to purchase the tfmini-plus lidar sensors so haven't had much time to use them. That being said I'm also trying to do a triple setup. That being said, how would I (as you mentioned in a previous comment above),  "after you assign and test unique and proper slave addresses for each of your LiDARs", do that code wise? Thanks

**Comment by Firestarter97** [comment]
@budryerson  Actually never mind. I realized you have a file called TFMPI2C_changeI2C.ino that helps search for other devices and helps change the address for those new devices. I've got a triple setup working. Thanks!

**Comment by digamesystems** [comment]
Cool! Looks like you are building a “poor man’s” 2-D LIDAR?

https://www.alliedelec.com/product/sick/tim551-2050001/71940124/?gclid=Cj0KCQjw06OTBhC_ARIsAAU1yOWluG6DGaMo6JZfR-JWPU1I7lHlrSnbjw2QI00TkF1432Q53zh_R4MaAiWzEALw_wcB&gclsrc=aw.ds

(That one only goes for $2600!)

John M. Price, Ph.D.
Digame Systems<diagamesystems.com> | 88 E San Fernando St. Ste. 1511, San Jose CA, 95113 | 408.840.9871 |
