### ISSUE TITLE
Max Distance

### ISSUE THREAD

**Issue by DConcord** [budryerson/TFMini-Plus#7]
First, thanks for your work on this library!

I'm replacing a TFMini with a TFMini plus. The TFMini would return a value of 65535 if the object was out of range, but the TFMini plus seems to return a value of 0, which is not super helpful in determining whether I'm dealing with an error in reading or just out of range. Is there a good way to differentiate?

thanks!

**Comment by budryerson** [comment]
I think that the strength of the returned signal might help differentiate between an error and a distance that's out of range.  Also the immediately adjacent readings can provide helpful clues.
